
version: '3.8'

services:
  youtube-downloader:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
